In [ ]:
import tensorflow as tf
tpu = tf.distribute.cluster_resolver.TPUClusterResolver.connect()
tpu_strategy = tf.distribute.TPUStrategy(tpu)

In [ ]:
!pip install transformers

In [ ]:
with open('/content/drive/MyDrive/english.txt') as f:
  l=f.readlines()

In [ ]:
l[:5]

['He is a 7th century king.\n',
 'This king belonged to the seventh century.\n',
 'This king belongs to seventh century.\n',
 'he is the king of 7th century\n',
 'Both these kingdoms did build fine temples.\n']

In [ ]:
l=[i[:-1] for i in l]

In [ ]:
l1=[]
for i in l:
  if len(i)>1:
    l1.append(i)

In [ ]:
l1[:5]

['He is a 7th century king.',
 'This king belonged to the seventh century.',
 'This king belongs to seventh century.',
 'he is the king of 7th century',
 'Both these kingdoms did build fine temples.']

In [ ]:
max(len(i) for i in l1)

2018

In [ ]:
from transformers import GPT2Tokenizer, TFGPT2Model

In [ ]:
tokenizer=GPT2Tokenizer.from_pretrained('gpt2')

DEBUG:filelock:Attempting to acquire lock 140661511642256 on /root/.cache/huggingface/transformers/684fe667923972fb57f6b4dcb61a3c92763ad89882f3da5da9866baf14f2d60f.c7ed1f96aac49e745788faa77ba0a26a392643a50bb388b9c04ff469e555241f.lock
DEBUG:filelock:Lock 140661511642256 acquired on /root/.cache/huggingface/transformers/684fe667923972fb57f6b4dcb61a3c92763ad89882f3da5da9866baf14f2d60f.c7ed1f96aac49e745788faa77ba0a26a392643a50bb388b9c04ff469e555241f.lock


Downloading:   0%|          | 0.00/0.99M [00:00<?, ?B/s]

DEBUG:filelock:Attempting to release lock 140661511642256 on /root/.cache/huggingface/transformers/684fe667923972fb57f6b4dcb61a3c92763ad89882f3da5da9866baf14f2d60f.c7ed1f96aac49e745788faa77ba0a26a392643a50bb388b9c04ff469e555241f.lock
DEBUG:filelock:Lock 140661511642256 released on /root/.cache/huggingface/transformers/684fe667923972fb57f6b4dcb61a3c92763ad89882f3da5da9866baf14f2d60f.c7ed1f96aac49e745788faa77ba0a26a392643a50bb388b9c04ff469e555241f.lock
DEBUG:filelock:Attempting to acquire lock 140661511642128 on /root/.cache/huggingface/transformers/c0c761a63004025aeadd530c4c27b860ec4ecbe8a00531233de21d865a402598.5d12962c5ee615a4c803841266e9c3be9a691a924f72d395d3a6c6c81157788b.lock
DEBUG:filelock:Lock 140661511642128 acquired on /root/.cache/huggingface/transformers/c0c761a63004025aeadd530c4c27b860ec4ecbe8a00531233de21d865a402598.5d12962c5ee615a4c803841266e9c3be9a691a924f72d395d3a6c6c81157788b.lock


Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

DEBUG:filelock:Attempting to release lock 140661511642128 on /root/.cache/huggingface/transformers/c0c761a63004025aeadd530c4c27b860ec4ecbe8a00531233de21d865a402598.5d12962c5ee615a4c803841266e9c3be9a691a924f72d395d3a6c6c81157788b.lock
DEBUG:filelock:Lock 140661511642128 released on /root/.cache/huggingface/transformers/c0c761a63004025aeadd530c4c27b860ec4ecbe8a00531233de21d865a402598.5d12962c5ee615a4c803841266e9c3be9a691a924f72d395d3a6c6c81157788b.lock
DEBUG:filelock:Attempting to acquire lock 140665640250000 on /root/.cache/huggingface/transformers/16a2f78023c8dc511294f0c97b5e10fde3ef9889ad6d11ffaa2a00714e73926e.cf2d0ecb83b6df91b3dbb53f1d1e4c311578bfd3aa0e04934215a49bf9898df0.lock
DEBUG:filelock:Lock 140665640250000 acquired on /root/.cache/huggingface/transformers/16a2f78023c8dc511294f0c97b5e10fde3ef9889ad6d11ffaa2a00714e73926e.cf2d0ecb83b6df91b3dbb53f1d1e4c311578bfd3aa0e04934215a49bf9898df0.lock


Downloading:   0%|          | 0.00/1.29M [00:00<?, ?B/s]

DEBUG:filelock:Attempting to release lock 140665640250000 on /root/.cache/huggingface/transformers/16a2f78023c8dc511294f0c97b5e10fde3ef9889ad6d11ffaa2a00714e73926e.cf2d0ecb83b6df91b3dbb53f1d1e4c311578bfd3aa0e04934215a49bf9898df0.lock
DEBUG:filelock:Lock 140665640250000 released on /root/.cache/huggingface/transformers/16a2f78023c8dc511294f0c97b5e10fde3ef9889ad6d11ffaa2a00714e73926e.cf2d0ecb83b6df91b3dbb53f1d1e4c311578bfd3aa0e04934215a49bf9898df0.lock
DEBUG:filelock:Attempting to acquire lock 140661506665424 on /root/.cache/huggingface/transformers/fc674cd6907b4c9e933cb42d67662436b89fa9540a1f40d7c919d0109289ad01.7d2e0efa5ca20cef4fb199382111e9d3ad96fd77b849e1d4bed13a66e1336f51.lock
DEBUG:filelock:Lock 140661506665424 acquired on /root/.cache/huggingface/transformers/fc674cd6907b4c9e933cb42d67662436b89fa9540a1f40d7c919d0109289ad01.7d2e0efa5ca20cef4fb199382111e9d3ad96fd77b849e1d4bed13a66e1336f51.lock


Downloading:   0%|          | 0.00/665 [00:00<?, ?B/s]

DEBUG:filelock:Attempting to release lock 140661506665424 on /root/.cache/huggingface/transformers/fc674cd6907b4c9e933cb42d67662436b89fa9540a1f40d7c919d0109289ad01.7d2e0efa5ca20cef4fb199382111e9d3ad96fd77b849e1d4bed13a66e1336f51.lock
DEBUG:filelock:Lock 140661506665424 released on /root/.cache/huggingface/transformers/fc674cd6907b4c9e933cb42d67662436b89fa9540a1f40d7c919d0109289ad01.7d2e0efa5ca20cef4fb199382111e9d3ad96fd77b849e1d4bed13a66e1336f51.lock


In [ ]:
len(tokenizer)

50257

In [ ]:
special_tokens_dict = {'cls_token': '<CLS>','unk_token':'<unk>','sep_token':'<sep>','pad_token':'<pad>','mask_token':'<mask>'}

In [ ]:
tokenizer.add_special_tokens(special_tokens_dict)

4

In [ ]:
len(tokenizer)

50261

In [ ]:
tokenizer.vocab_size

50257

In [ ]:
tokenizer.unk_token_id

In [ ]:
inputs=tokenizer(l1, padding='max_length',max_length=100,truncation=True)

In [ ]:
inputs.keys()

dict_keys(['input_ids', 'attention_mask'])

In [ ]:
q=inputs['input_ids']
q1=inputs['attention_mask']

In [ ]:
q[0]

In [ ]:
y=[q[i][1:]+[50259] for i in range(len(q))]

In [ ]:
import numpy as np

In [ ]:
q=np.array(q)
q1=np.array(q1)
y=np.array(y)

In [ ]:
q.shape

(42987, 100)

In [ ]:
y.shape

(42987, 100)

In [ ]:
from transformers import GPT2Config

In [ ]:
config=GPT2Config.from_pretrained('gpt2')

In [ ]:
with tpu_strategy.scope():
  model=TFGPT2Model(config=config)

In [ ]:
with tpu_strategy.scope():
  model.resize_token_embeddings(len(tokenizer))

In [ ]:
from keras import Model
from keras.layers import Input, Activation, Flatten,LSTM,Dense

In [ ]:
with tpu_strategy.scope():
  inp1=Input(shape=(100,),dtype='int32')
  inp2=Input(shape=(100,),dtype='int32')
  emb=model(inp1,attention_mask=inp2)[0]
  x=Dense(len(tokenizer),activation='softmax')(emb)
  m=Model(inputs=[inp1,inp2],outputs=x)

In [ ]:
m.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 100)]        0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, 100)]        0                                            
__________________________________________________________________________________________________
tfgp_t2model (TFGPT2Model)      TFBaseModelOutputWit 124442880   input_1[0][0]                    
                                                                 input_2[0][0]                    
__________________________________________________________________________________________________
dense (Dense)                   (None, 100, 50261)   38650709    tfgp_t2model[0][0]           

In [ ]:
emb.shape

TensorShape([None, 100, 768])

In [ ]:
import keras

In [ ]:
with tpu_strategy.scope():
  m.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=3e-5),loss=keras.losses.SparseCategoricalCrossentropy(),metrics=['accuracy'])

In [ ]:
with tpu_strategy.scope():
  m.fit([q,q1],y,epochs=1,batch_size=32,validation_split=0.15)

1142/1142 [==============================] - ETA: 0s - loss: 1.4904 - accuracy: 0.8428

INFO:absl:TPU has inputs with dynamic shapes: [<tf.Tensor 'Const:0' shape=() dtype=int32>, <tf.Tensor 'cond_8/Identity:0' shape=(None, 100) dtype=int64>, <tf.Tensor 'cond_8/Identity_1:0' shape=(None, 100) dtype=int64>, <tf.Tensor 'cond_8/Identity_2:0' shape=(None, 100) dtype=int64>]


1142/1142 [==============================] - 129s 113ms/step - loss: 1.4904 - accuracy: 0.8428 - val_loss: 1.2163 - val_accuracy: 0.8476


In [ ]:
SEED=34

In [ ]:
import tensorflow as tf
tf.random.set_seed(SEED)

In [ ]:
text='you are going to'

In [ ]:
input_ids=tokenizer.encode(text, return_tensors='tf')

In [ ]:
input_ids

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[5832,  389, 1016,  284]], dtype=int32)>

In [ ]:
sample_output=model.generate(input_ids,
                             do_sample= True,
                             max_length=25,
                             temprature=0.70,
                             top_k=15,
                             top_p=0.85,)

In [ ]:
sample_output

<tf.Tensor: shape=(1, 25), dtype=int32, numpy=
array([[ 5832,   389,  1016,   284,   766,   588,   428,    13, 50259,
        50259, 50259,  8117,   389,  1115,  1180,  3354,   286,  5770,
           11,  5770,  1061,   262,  5737,  3891,   287]], dtype=int32)>

In [ ]:
tokenizer.decode(sample_output[0], skip_special_tokens=True)

'you are going to see like this.there are three different parts of god, god follow the religion names in'

In [ ]:
save_locally = tf.saved_model.SaveOptions(experimental_io_device='/job:localhost')
m.save_weights('/content/drive/MyDrive/my_model_weights/Text_Generation_GPT-2', options=save_locally)

In [ ]:
input_ids = tokenizer.encode(text, return_tensors='tf')

beam_output = model.generate(
  input_ids,
  max_length = 25,
  num_beams=2,
  temperature=0.85,
)

In [ ]:
beam_output

<tf.Tensor: shape=(1, 25), dtype=int32, numpy=
array([[ 5832,   389,  1016,   284,  1011,  1337,   286,   262,  1767,
          286,  1767,    13, 50259, 50259, 50259, 50259,   271,   351,
          503,  2089,   661,   286,  1767,    11,   661]], dtype=int32)>

In [ ]:
res=[]
for i in beam_output:
  p=[]
  for j in i.numpy():
    if not (j==50259):
      p.append(j)
  res.append(p)

In [ ]:
res

[[5832,
  389,
  1016,
  284,
  1011,
  1337,
  286,
  262,
  1767,
  286,
  1767,
  13,
  271,
  351,
  503,
  2089,
  661,
  286,
  1767,
  11,
  661]]

In [ ]:
print(tokenizer.decode(res[0]))

you are going to take care of the body of body.is with out bad people of body, people


In [ ]:
m.save_weights('/content/drive/MyDrive/my_model_weights/Text_Generation_GPT-2')

In [ ]:
m.load_weights('/content/drive/MyDrive/my_model_weights/Text_Generation_GPT-2')